---
title: "Draft Manuscript"
author: "Samme Senekal"
date: "2026-02-06"
output: pdf_document
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction 

Start with a definition of theophylline and what it is used for (make a citation here). Introduce pharmacokinetics ([@barnes2010]).

Talk about why the pharmacokinetics of this drug are important and what your little manuscript will show about theophylline. This manuscript will be determining if the half-life of theophylline is affected by a patients body weight. Talk about what half-life is regarding drugs and why it is important to know the half-life (citation). Bring up how pharmacokinetics of some drugs depends on patient body  

#Results

Add your graphs here and make a figure legend. Talk about the statistics and if it was significant or not.

#Discussion

Talk about why half-life of theophylline does not depend on patient weight and what it depends on instead.


::: {#refs}
:::
